export const SET_REGISTER_DATA = 'SET_REGISTER_DATA'
export const SET_REGISTER_DATA_SUCCESS = 'SET_REGISTER_DATA_SUCCESS'

export const SET_USER_NAME = 'SET_USER_NAME'
export const SET_USER_NAME_SUCCESS = 'SET_USER_NAME_SUCCESS'

export const SET_USER_EMAIL = 'SET_REGISTER_EMAIL'
export const SET_USER_EMAIL_SUCCESS = 'SET_REGISTER_EMAIL_SUCCESS'

export const SET_USER_PHONE = 'SET_REGISTER_PHONE'
export const SET_USER_PHONE_SUCCESS = 'SET_REGISTER_PHONE_SUCCESS'

export const SET_USER_PIN_CODE = 'SET_ACCOUNT_PIN_CODE'
export const SET_USER_PIN_CODE_SUCCESS = 'SET_ACCOUNT_PIN_CODE_SUCCESS'

export const SET_USER = 'SET_USER'
export const SET_USER_SUCCESS = 'SET_USER_SUCCESS'
export const SET_USER_FAIL = 'SET_USER_FAIL'

export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'

export const FETCH_SECURITY_SETTINGS = 'FETCH_SECURITY_SETTINGS'
export const FETCH_SECURITY_SETTINGS_SUCCESS = 'FETCH_SECURITY_SETTINGS_SUCCESS'
export const FETCH_SECURITY_SETTINGS_FAILURE = 'FETCH_SECURITY_SETTINGS_FAILURE'

export const SET_LOGIN = 'SET_LOGIN'
export const SET_LOGIN_SUCCESS = 'SET_LOGIN_SUCCESS'

export const SET_LOGOUT = 'SET_LOGOUT'
export const SET_LOGOUT_SUCCESS = 'SET_LOGOUT_SUCCESS'

export const SET_ACCOUNT_PIN_CODE = 'SET_ACCOUNT_PIN_CODE'
export const SET_ACCOUNT_PIN_CODE_SUCCESS = 'SET_ACCOUNT_PIN_CODE_SUCCESS'

export const PHONE_VERIFICATION_CODE_LENGTH = 6

export const GET_SMS_VERIFICATION_CODE = 'GET_SMS_VERIFICATION_CODE'
export const GET_SMS_VERIFICATION_CODE_SUCCESS = 'GET_SMS_VERIFICATION_CODE_SUCCESS'
export const GET_SMS_VERIFICATION_CODE_FAILURE = 'GET_SMS_VERIFICATION_CODE_FAILURE'

export const SEND_VERIFICATION_CODE = 'SEND_VERIFICATION_CODE'
export const SEND_VERIFICATION_CODE_SUCCESS = 'SEND_VERIFICATION_CODE_SUCCESS'
export const SEND_VERIFICATION_CODE_FAILURE = 'SEND_VERIFICATION_CODE_FAILURE'

export const SET_REMEMBER_DEVICE = 'SET_REMEMBER_DEVICE'
export const SET_REMEMBER_DEVICE_SUCCESS = 'SET_REMEMBER_DEVICE_SUCCESS'

export const SECURITY_SETTING = 'SECURITY_SETTING'
export const SECURITY_SETTING_SUCCESS = 'SECURITY_SETTING_SUCCESS'

export const CAMERA_ON = 'CAMERA_ON'
export const CAMERA_OFF = 'CAMERA_OFF'

export const SET_OVERLAY = 'SET_OVERLAY'
export const SET_OVERLAY_SUCCESS = 'SET_OVERLAY_SUCCESS'

